Add ability to reflect whitelisted labels
emberstack/kubernetes-reflector pull request #464
Opened 2024-09-18 14:34 UTC by Valtaroth

Following feature request https://github.com/emberstack/kubernetes-reflector/discussions/414 I added the option to have labels mirrored based on two new annotations, `<prefix>/reflection-labels` and `<prefix>/reflection-labels-included`.

By default the functionality stays exactly the same with just the content being mirrored. However, once `<prefix>/reflection-labels` is set to true the source labels will be included in the mirror. `<prefix>/reflection-labels-included` is a regex list like already used for namespace whitelisting which can be used to finely filter the labels to be mirrored, for example to only mirror labels prefixed with `example.com/`:
```yaml
annotations:
  reflector.v1.k8s.emberstack.com/reflection-labels: "true"
  reflector.v1.k8s.emberstack.com/reflection-labels-included: "example\\.com/.*"
```

2025-02-23 11:07 UTC, winromulus requested changes
Please also update the documentation (README) and rebase on the latest version

2025-02-24 06:52 UTC, valtaroth commented
Thanks for considering my pull request, I've updated the documentation with my addition and rebased to latest. Please let me know if you require more changes.

2025-03-25 07:16 UTC, valtaroth commented
I rebased again and integrated my changes with the latest refactoring.

2025-05-01 09:06 UTC, valtaroth commented
@winromulus was there anything else you need me to do for this PR or has it been rejected?

2025-05-01 09:10 UTC, winromulus commented
hey @valtaroth I'm currently upgrading the repository a bit and then I'll start the review on this again. There is a similar PR with reflecting source annotations and labels, and I also need to consider a feature flag for this to maintain compatibility (basically a merge of the two PRs with a flag). Currently setting up some automation for this and I'll resume reviews after

2025-05-01 10:03 UTC, valtaroth commented
I understand, thank you for updating me!

2025-05-08 15:07 UTC, deens-cyera commented
Hey, any update on this?

2025-06-07 00:02 UTC, closed without merging

2026-01-27 16:21 UTC, ElhoubeBrahim commented
Ping ... This would be a helpful feature!